export const USER_LOADED               = "USER_LOADED"
export const AUTH_ERROR                = "AUTH_ERROR"     
export const LOGIN_SUCCESS             = "LOGIN_SUCCESS" 
export const LOGIN_FAIL                = "LOGIN_FAIL"
export const CLEAR_PROFILE             = "CLEAR_PROFILE" 
export const LOGOUT                    = "LOGOUT"
export const REGISTER_SUCCESS          = "REGISTER_SUCCESS"
export const REGISTER_FAIL             = "REGISTER_FAIL"
export const BIND_TABLE_COUNTRY        = "BIND_TABLE_COUNTRY"
export const BIND_TABLE_STATE          = "BIND_TABLE_STATE"
export const BIND_TABLE_CITY           = "BIND_TABLE_CITY"
export const BIND_TABLE_GENDER         = "BIND_TABLE_GENDER"
export const BIND_TABLE_ERROR          = "BIND_TABLE_ERROR"
export const EMPLOYE_PROFILE_UPDATE                  = "EMPLOYE_PROFILE_UPDATE"
export const EMPLOYE_PROFILE_UPDATE_SUCCESS          = "EMPLOYE_PROFILE_UPDATE_SUCCESS"
export const EMPLOYE_PROFILE_UPDATE_FAIL             = "EMPLOYE_PROFILE_UPDATE_FAIL"

